In [ ]:
!pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=5142061a4c6f50c4599a31ccd1714222e05665e269861c3a7069a699171e5f39
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


In [ ]:
A=np.ones((8,4))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#importing
import numpy as np
# random module is sub package of numpy

In [ ]:
A=np.random.rand(1)  # it can give any random value
print(A)

[0.85679246]


In [ ]:
A=np.random.rand(8,4)  #rand range is between 0 and 1
print(A)

[[0.61629809 0.70735843 0.95626109 0.75952874]
 [0.2515398  0.66824857 0.80077212 0.21017178]
 [0.244218   0.81272213 0.09294277 0.15991081]
 [0.00242939 0.7768135  0.13343022 0.98759122]
 [0.63161207 0.36020394 0.6711001  0.21636172]
 [0.83372965 0.45162371 0.73643434 0.11253632]
 [0.22684809 0.06506939 0.01297308 0.01510649]
 [0.06183356 0.08007894 0.09426829 0.38027241]]


In [ ]:
A=10*np.random.rand(8,4)  #rand range is between 0 and 1
print(A)

[[3.50959985 9.36262695 1.37713666 2.18739834]
 [7.43506776 2.46053586 1.31496076 5.22842184]
 [6.45403195 8.94297474 9.57638047 6.64056694]
 [2.96760118 1.90024468 5.23591261 5.34550758]
 [8.52389118 8.46662247 8.3065015  1.75954656]
 [7.17653713 1.36099645 5.34217652 7.59056088]
 [3.563413   2.08905906 4.18908985 9.27892264]
 [5.24957268 8.60280776 1.81012311 7.79511162]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))  #rand range is between 0 and 1
print(A)

[[7. 7. 0. 4.]
 [8. 2. 0. 2.]
 [6. 9. 8. 7.]
 [0. 7. 1. 6.]
 [9. 6. 6. 9.]
 [9. 1. 3. 5.]
 [7. 3. 2. 5.]
 [1. 9. 4. 5.]]


In [ ]:
np.vsplit(A,4)

[array([[7., 7., 0., 4.],
        [8., 2., 0., 2.]]),
 array([[6., 9., 8., 7.],
        [0., 7., 1., 6.]]),
 array([[9., 6., 6., 9.],
        [9., 1., 3., 5.]]),
 array([[7., 3., 2., 5.],
        [1., 9., 4., 5.]])]

In [ ]:
np.vsplit(A,(2,4))  #split it after 2nd row and 4th row

[array([[7., 7., 0., 4.],
        [8., 2., 0., 2.]]),
 array([[6., 9., 8., 7.],
        [0., 7., 1., 6.]]),
 array([[9., 6., 6., 9.],
        [9., 1., 3., 5.],
        [7., 3., 2., 5.],
        [1., 9., 4., 5.]])]

In [ ]:
np.hsplit(A,4)

[array([[7.],
        [8.],
        [6.],
        [0.],
        [9.],
        [9.],
        [7.],
        [1.]]),
 array([[7.],
        [2.],
        [9.],
        [7.],
        [6.],
        [1.],
        [3.],
        [9.]]),
 array([[0.],
        [0.],
        [8.],
        [1.],
        [6.],
        [3.],
        [2.],
        [4.]]),
 array([[4.],
        [2.],
        [7.],
        [6.],
        [9.],
        [5.],
        [5.],
        [5.]])]

In [ ]:
np.hsplit(A,(1,3))

[array([[7.],
        [8.],
        [6.],
        [0.],
        [9.],
        [9.],
        [7.],
        [1.]]),
 array([[7., 0.],
        [2., 0.],
        [9., 8.],
        [7., 1.],
        [6., 6.],
        [1., 3.],
        [3., 2.],
        [9., 4.]]),
 array([[4.],
        [2.],
        [7.],
        [6.],
        [9.],
        [5.],
        [5.],
        [5.]])]

In [ ]:
B=np.arange(1,33,1).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,8)

[array([[ 1],
        [ 9],
        [17],
        [25]]),
 array([[ 2],
        [10],
        [18],
        [26]]),
 array([[ 3],
        [11],
        [19],
        [27]]),
 array([[ 4],
        [12],
        [20],
        [28]]),
 array([[ 5],
        [13],
        [21],
        [29]]),
 array([[ 6],
        [14],
        [22],
        [30]]),
 array([[ 7],
        [15],
        [23],
        [31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.hsplit(B,(2,4)) #split it after 2nd column ND 4TH column

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A) #convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:
a=([ 45.,  60.,  90., 180.])
np.deg2rad(a)


array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
np.cos(90)

-0.4480736161291701

In [ ]:
np.tan(45)

1.6197751905438615

statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)


46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)
#std=root(sigma(xi-mu)/N)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
D=np.arange(1,5).reshape(2,2)
print(D)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(D)   #it is the sub package of numpy It gives the inverse of the given array

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.random.rand(2,6).reshape(6,2)
print(C)

[[0.68733346 0.25680588]
 [0.32120442 0.4087346 ]
 [0.19660866 0.64430222]
 [0.73569492 0.48414434]
 [0.27018948 0.43848571]
 [0.17502421 0.14472284]]


In [ ]:
print(np.argmax(C))

6


In [ ]:
np.argmax(C,axis=1) #gives the index number where it has biggest value in each row

array([0, 1, 1, 0, 1, 0])

In [ ]:
np.argmax(C,axis=0) #gives the index number where it has biggest value in each columns

array([3, 2])

In [ ]:
print(np.argmin(C))

11


In [ ]:
print(np.argmin(C,axis=1))

[1 0 0 1 0 1]


In [ ]:
print(np.argmin(C,axis=0))

[5 5]


searching

In [ ]:
a=np.array([34,45,67,89,23])
print(np.where(a>49))

(array([2, 3]),)


In [ ]:
print(np.where(a/8==0))

(array([], dtype=int64),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
z=np.array([23,34,45,56,67])
y=np.searchsorted(z,56)
print(y)

3


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.sort(a))
c=np.searchsorted(a,24)
print(c)

[ 7 16 17 24 54 60]
4


In [ ]:
arr=np.array(["banana","apple","cherry"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
q=np.array([True,False,False])
print(np.sort(q))


[False False  True]


In [ ]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


array filter

In [ ]:
arr=np.array([40,34,57,89,90])   #filter can work for arrays and lists
flit=np.where(arr%2==0)
print(flit)

(array([0, 1, 4]),)


In [ ]:
arr[flit]

array([40, 34, 90])

iterating two arrays

In [ ]:
names=np.array(["Vyshu","Bhargavi","Devi","Satya"])
initials=np.array(["Y","P","M","A"])
for i,j in zip(initials,names):
  print(i,".",j)

Y . Vyshu
P . Bhargavi
M . Devi
A . Satya


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([2,3,4,5,6,7])
n=np.multiply(a1,a2)
print(n)


[ 20  60 120 200 300 420]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([2,3,4,5,6,7])
n=np.divmod(a1,a2)
print(n)

(array([5, 6, 7, 8, 8, 8]), array([0, 2, 2, 0, 2, 4]))


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([2,3,4,5,6,7])
n=np.mod(a1,a2)
print(n)

[0 2 2 0 2 4]


In [ ]:
a1=np.array([2,3,4,5,6,7])
a2=np.array([10,20,30,40,50,60])
n=np.subtract(a1,a2)
print(n)


[ -8 -17 -26 -35 -44 -53]


Logarithms

In [ ]:
a1=np.arange(1,10)
print(a1)
print("\n")
print(np.log2(a1)) #log with base 2
print("\n")
print(np.log10(a1)) #log with base 10
print("\n")
print(np.log(a1)) #natural logarithms

[1 2 3 4 5 6 7 8 9]


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


Other Mathematical Functions

In [ ]:
a2=np.array([24,46,68,80])
z=np.cumsum(a2)
print(z)

[ 24  70 138 218]


In [ ]:
a1=np.array([2,4,6,8,10])
z=np.cumprod(a1)
print(z)

[   2    8   48  384 3840]


In [ ]:
a1=np.array([2,4,6,8,10])
z=np.diff(a1)
print(z)

[2 2 2 2]


In [ ]:
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)
y=np.gcd(n1,n2)
print(y)

8645
35


In [ ]:
a=np.array([12,13,14])
gc=np.gcd.reduce(a)  #takes multiple inputs gives single output
print(gc)

TypeError: gcd() takes from 2 to 3 positional arguments but 1 were given

In [ ]:
a=np.array([12,13,14])
gc=np.lcm.reduce(a)  #takes multiple inputs gives single output
print(gc)

1092
